site_name: My Code Snippets
nav:
    - Home: index.md
    - 標準入出力 : input_output.md
    - ユークリッドの互除法 : gcd_lcm.md
    - 素因数分解 : prime_factorization.md

theme:
    name: 'material'

markdown_extensions:
    - codehilite
    - mdx_math:
        enable_dollar_delimiter: true
    - admonition

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/config/TeX-AMS-MML_HTMLorMML-full.js

site_author: kira924age
copyright: Copyright © 2019 kira924age

